New health bar
kepler471/moonshot pull request #227
Opened 2020-11-28 19:13 UTC by whitew1994WW

New cool plunger

2020-11-28 23:29 UTC, wattsit commented
![image](https://user-images.githubusercontent.com/67764860/100528166-7b361580-31d1-11eb-92fa-ea77000da994.png)
in `HUD.gd` returns null.

I think you need to include the changes to the `main_game.tscn`

2020-11-28 23:31 UTC, wattsit requested changes
Needs the changes to `main_game.tscn` included in the pull.

2020-11-29 13:56 UTC, kepler471 approved these changes

2020-11-29 14:01 UTC, Jamesbarford requested changes

2020-11-29 14:01 UTC, Jamesbarford commented on Moonshot/HUD.gd
> +	var new_health_bar_size = (Utils.player_stats.health*152) / Utils.player_stats.max_health
Can we make make the magic numbers constants?

2020-11-29 14:04 UTC, Jamesbarford commented on Moonshot/HUD.gd
> +	var new_health_bar_size = (Utils.player_stats.health*152) / Utils.player_stats.max_health
For the next pr

2020-11-29 14:18 UTC, merged